### ISSUE TITLE
Disable default NER models in CoreNLP output

### ISSUE THREAD

**Issue by wkiri** [wkiri/MTE#13]

**Comment by stevenlujpl** [comment]
@wkiri Done. All of the default NER models should have been disabled now. I have pushed the changes to the parser-indexer repo, and pulled the changes to the code in `/proj/mte/parser-indexer-py/`. 

The default NER models need to be disabled from the config and script levels. The built-in NER models can be disabled in the CoreNLP config files used for starting up the server, however, the fine grained location NER model (newly introduced in v4.2.0 and is enabled by default) has to be disabled in the python script.  

I think this issue can be closed. I will leave it open until you have an opportunity to test it.

**Comment by wkiri** [comment]
I re-generated PHX output and confirmed that the fine-grained NER model output is now gone.  

I have not updated our saved results/brat files.  We don't want to over-write them because they have edits from brat.  The additional entities increase the size of the `.ann` files but are ignored when generating our MTE databases so I think it is fine to leave as-is.
