### ISSUE TITLE
Update ingest_sqlite.py to remove LPSC-specific content

### ISSUE THREAD

**Issue by wkiri** [wkiri/MTE#18]
To support non-LPSC content (like journals), we will need to update these functions:

https://github.com/wkiri/MTE/blob/314723342febecd90ccac5a6581c6af9353407d3/src/ingest_sqlite.py#L93-L113

**Comment by stevenlujpl** [comment]
@wkiri I added a command line argument `-v` or `--venue` to the `ingest_sqlite.py` script to make populating LPSC-specific content optional. The `-v` or `--venue` argument accepts a string from the list `[lpsc, others]`, and the default is `others` (which means doing nothing for the `doc_url` and `venue` fields). If we run the `ingest_sqlite.py` with `-v=lpsc` or `--venue=lpsc` option, then the fields `doc_url` and `venue` will be populated by calling the `construct_doc_url()` and `update_doc_venue()` functions. For example,

```
python ingest_sqlite.py lpsc.jsonl  -d lpsc.db -v lpsc
```

**Comment by wkiri** [comment]
I ran this on PHX and MER-A content and it works as expected.  Thanks!

**Comment by wkiri** [comment]
PHX was run before the ADS updates so 'venue' is empty if run without -v lpsc.
