### ISSUE TITLE
Update jsre_parser.py to skip jSRE if no records to classify

### ISSUE THREAD

**Issue by wkiri** [wkiri/MTE#29]

**Comment by wkiri** [comment]
This run caused ~15 jSRE "no input file" errors:
```Console
$ export JSON_FILE=/proj/mte/results/mer-a-jsre-v2-ads.jsonl
$ export JSRE_MODEL=/proj/mte/trained_models/jSRE-lpsc15-merged-binary.model
$ export NER_MODEL=/proj/mte/trained_models/ner_MERA-property-salient.ser.gz
$ python ../../git/src/lpsc_parser.py -li pdfpaths-$MISSION.list -o $JSON_FILE -jr /proj/mte/jSRE/jsre-1.1 -jm $JSRE_MODEL -n $NER_MODEL
```

**Comment by wkiri** [comment]
@youlu I went hunting and found another `lpsc_parser.py` process running on `mlia-compute` with my username (!).  I can't find where it was running from (it was not in any active screens), but I terminated the process.  I suspect this was causing the failures above.  I will re-run and let you know if I see any further issues.

**Comment by wkiri** [comment]
@stevenlujpl This run completed with no errors.  I suspect that the other process caused the errors above, so please do not worry about spending time on them.  I think that the `open()` call must be creating an (empty) input file for jSRE so we do not see an error even if `records` is empty.  I think it would be nice to skip the call to jSRE in that case, but it is not a critical change at this time.  If you agree, feel free to close this issue.  If however it is an easy addition to skip jSRE for empty `records`, I think it is a nice update and might shorten runtime a bit.

**Comment by stevenlujpl** [comment]
I confirmed that `io.open()` call will create an empty file when the `records` variable is empty, and I also added the check to skip jSRE call if there is no target-element and target-mineral record.

**Comment by wkiri** [comment]
Excellent!
